"""
Django settings for cms_site project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from configparser import ConfigParser
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#CMS 
SITE_ID = 1
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
cfg = ConfigParser()
cfg.read(os.path.join(BASE_DIR,'keys.ini'))
SECRET_KEY = cfg['DJANGO']['SECRET_KEY']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'cms_site.User'
# Application definition

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django_light',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'sekizai',
    'cms_site',
    'cms',
    'post_cms', #post cms init logic goes here
    'menus',
    'treebeard',
    'filer',
    'easy_thumbnails',
    'mptt',
    'djangocms_text_ckeditor',
    'djangocms_link',
    'djangocms_file',
    'djangocms_picture',
    'djangocms_video',
    'djangocms_googlemap',
    'djangocms_snippet',
    'djangocms_style',
    'django.forms',

]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'cms.middleware.utils.ApphookReloadMiddleware',
    'cms_site.middleware.data.DataMiddleware',
    'cms_site.middleware.ware.WareMiddleware',
    'cms_site.middleware.auth.AuthMiddleware',
]

ROOT_URLCONF = 'cms_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sekizai.context_processors.sekizai',
                'cms.context_processors.cms_settings',
                'django.template.context_processors.i18n',
                'cms_site.context_processors.data'
            ],
        },
    },
]

WSGI_APPLICATION = 'cms_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'django-cms-store-db',
        'USER': 'postgres',
        'PASSWORD': cfg['DATABASE']['PASSWORD'],
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    Path(BASE_DIR, 'static'),
    Path(BASE_DIR, 'static/assets')
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

CMS_TEMPLATES = [
    ('template.html', 'Base Template'),
    ('index.html', 'Index Template'),
    ('contact.html', 'Contact Template'),
    ('about.html', 'About Template'),
    ('ware-info.html', 'Ware Info Template'),
    ('cart.html', 'Cart Page Template'),
    ('components/ware.html', 'Ware Template'),
    ('components/ware-preview.html', 'Ware Preview Template'),
    ('forms/signin.html', 'Sign In Form'),
    ('forms/signup.html', 'Sign Up Form'),
    ('forms/email-change.html', 'Email Change Form'),
    ('forms/pwd-reset1.html', 'First Step Password Reset Form'),
    ('forms/pwd-reset2.html', 'Second Step Password Reset Form'),
    ('forms/status-page.html', 'Status Page'),
    ('dev/data-page.html', 'Dev Data Page'),
    ('components/gallery.html', 'Showcase Test (Remove and Add through include)'),
]

DJANGOCMS_SNIPPET_SEARCH = True

CMS_PAGE_CACHE = False 

THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)
THUMBNAIL_ALIASES = {
    '': {
        'showcase': {'size': (640, 360), 'crop': 'scale'},
        'item_showcase': {'size': (1280, 720), 'crop': 'scale'},
        'gallery_small': {'size': (196, 196), 'crop': 'scale'},
        'gallery_big': {'size': (640, 640), 'crop': 'scale'},
        'max_size': {'size': (1920, 1920), 'crop': 'scale'},
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LANGUAGES = [
    ('en-us', 'English'),
    ('ru', 'Russian'),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

# Custom 

# Set to True for tes runs so we don't spam emails
SKIP_MAILING = False

